---
title: "scUnifrac Report"
header-includes:
   - \usepackage{float}
output: 
  pdf_document:
    toc: true
    number_sections: true
params:
  data: plotData
  outFile: outputFile
  contentFile: contentFile
---

```{r setup, include=FALSE}

options(knitr.table.format = "latex")

figRef <- local({
  tag <- numeric()
  created <- logical()
  used <- logical()
  function(label, caption, prefix = options("figcap.prefix"), 
           sep = options("figcap.sep"), prefix.highlight = options("figcap.prefix.highlight")) {
    i <- which(names(tag) == label)
    if (length(i) == 0) {
      i <- length(tag) + 1
      tag <<- c(tag, i)
      names(tag)[length(tag)] <<- label
      used <<- c(used, FALSE)
      names(used)[length(used)] <<- label
      created <<- c(created, FALSE)
      names(created)[length(created)] <<- label
    }
    if (!missing(caption)) {
      created[label] <<- TRUE
      return(caption)
    } else {
      used[label] <<- TRUE
      return(tag[label])
    }
  }
})
options(figcap.prefix = "Figure", figcap.sep = ":", figcap.prefix.highlight = "**")

tabRef <- local({
  tag <- numeric()
  created <- logical()
  used <- logical()
  function(label, caption) {
    i <- which(names(tag) == label)
    if (length(i) == 0) {
      i <- length(tag) + 1
      tag <<- c(tag, i)
      names(tag)[length(tag)] <<- label
      used <<- c(used, FALSE)
      names(used)[length(used)] <<- label
      created <<- c(created, FALSE)
      names(created)[length(created)] <<- label
    }
    if (!missing(caption)) {
      created[label] <<- TRUE
      return(caption)
    } else {
      used[label] <<- TRUE
      return(tag[label])
    }
  }
})

plotData<-params$data
outputFile<-params$outFile
contentFile<-params$contentFile
DISPLAY_FIGURE<-TRUE
hasDiffnodes<-length(plotData$diffnodes) > 0
subRmd<-paste0(outputFile, "_subpopulation.rmd")

```

```{r child=contentFile, echo=FALSE}
```
